"""GIF animation helpers for LRB/RB result sweeps.

This module adds notebook-friendly animation utilities that consume existing
CSV outputs generated by ``LRBResultsPlotter`` and write GIF artifacts under a
run's ``results/plots/gifs`` directory.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import re

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, PillowWriter
from matplotlib.lines import Line2D

from .lrb_plotting import LRBResultsPlotter


@dataclass(frozen=True)
class LRBGifRenderConfig:
    """
    Rendering controls for notebook GIF generation.

    Attributes:
        fps (int): Target GIF frame rate.
        dpi (int): Render resolution used when encoding GIF frames.
        figsize_const (tuple[float, float]): Figure size for const-sweep GIFs.
        figsize_unif (tuple[float, float]): Figure size for interval-sweep
            GIFs.
        hold_frames (int): Number of repeated keyframes per anchor state.
        transition_frames (int): Number of interpolated transition frames
            inserted between adjacent anchor states.

    Methods:
        This dataclass is declarative and defines no custom methods.
    """

    fps: int = 10
    dpi: int = 120
    figsize_const: tuple[float, float] = (7.6, 4.8)
    figsize_unif: tuple[float, float] = (11.0, 4.6)
    hold_frames: int = 1
    transition_frames: int = 6


class LRBGifAnimator:
    """
    Build animation GIFs from one loaded ``LRBResultsPlotter`` run.

    Attributes:
        plotter (LRBResultsPlotter): Source plotter that provides run metadata
            and CSV loading helpers.
        render_config (LRBGifRenderConfig): Rendering options used for GIF
            generation.
        out_dir (Path): Output directory where GIF files are written.

    Methods:
        create_const_sweep_gif(...): Build one GIF sweeping all probabilities
            for a fixed constant check.
        create_unif_interval_sweep_gif(...): Build one GIF for a fixed
            probability while sweeping uniform interval checks.
        create_unif_interval_gifs_for_all_probabilities(...): Build interval
            sweep GIFs for every probability index.
    """
    _CODE_BRACKET_BY_NAME: dict[str, str] = {
        "folded_qutrit": "[[5,1,2]]",
        "qgrm_3_1_2": "[[3,1,2]]",
    }

    def __init__(
        self,
        plotter: LRBResultsPlotter,
        out_dir: str | Path | None = None,
        render_config: LRBGifRenderConfig | None = None,
    ) -> None:
        """
        Initialize one GIF animator bound to a prepared results plotter.

        Args:
            plotter (LRBResultsPlotter): Plotter instance with loaded run
                metadata and CSV readers.
            out_dir (str | Path | None): Optional GIF output directory. When
                ``None``, defaults to ``<plotter.out_dir>/gifs``.
            render_config (LRBGifRenderConfig | None): Optional render
                settings. Defaults to ``LRBGifRenderConfig()``.

        Returns:
            None: Constructor populates object state.

        Raises:
            OSError: Propagated if output-directory creation fails.
        """
        self.plotter = plotter
        self.render_config = render_config or LRBGifRenderConfig()
        target = (
            Path(out_dir)
            if out_dir is not None
            else Path(self.plotter.out_dir) / "gifs"
        )
        target.mkdir(parents=True, exist_ok=True)
        self.out_dir = target

    def _code_label(self) -> str:
        """
        Build a code label in ``[[n,k,d]]_q`` format for legend text.

        Args:
            None: Uses loaded plotter metadata.

        Returns:
            str: Code label in bracket-underscore format.

        Raises:
            ValueError: Not raised directly by this method.
        """
        code_name = str(getattr(self.plotter, "code_name", ""))
        bracket = self._CODE_BRACKET_BY_NAME.get(code_name, "")

        if bracket == "":
            match_name = re.search(r"(\d+)_(\d+)_(\d+)", code_name)
            if match_name:
                bracket = (
                    f"[[{match_name.group(1)},"
                    f"{match_name.group(2)},"
                    f"{match_name.group(3)}]]"
                )

        if bracket == "":
            code_title = str(getattr(self.plotter, "code_title", "")).replace(
                "$", ""
            )
            match_title = re.search(r"\[\[\d+,\d+,\d+\]\]", code_title)
            if match_title:
                bracket = match_title.group(0)

        if bracket == "":
            bracket = "[[n,k,d]]"

        q_dim = int(getattr(self.plotter, "d_dim", 3))
        return f"{bracket}_{q_dim}"

    def _lrb_label(self) -> str:
        """
        Build the LRB legend label with code metadata.

        Args:
            None: Uses loaded plotter metadata.

        Returns:
            str: Legend label text for LRB traces.

        Raises:
            ValueError: Not raised directly by this method.
        """
        return f"LRB on {self._code_label()}"

    @staticmethod
    def _default_curve_colors() -> tuple[str, str]:
        """
        Return the first two colors from the active Matplotlib cycle.

        This matches the default colors used by ``LRBResultsPlotter`` when
        plotting LRB then RB without explicit color overrides.

        Args:
            None: Uses global Matplotlib runtime configuration.

        Returns:
            tuple[str, str]: ``(lrb_color, rb_color)``.

        Raises:
            ValueError: Not raised directly by this method.
        """
        palette = plt.rcParams.get("axes.prop_cycle").by_key().get(
            "color",
            [],
        )
        if len(palette) >= 2:
            return str(palette[0]), str(palette[1])
        if len(palette) == 1:
            return str(palette[0]), "#ff7f0e"
        return "#1f77b4", "#ff7f0e"

    @staticmethod
    def _build_transition_frame_specs(
        num_keyframes: int,
        hold_frames: int,
        transition_frames: int,
    ) -> list[tuple[int, int, float]]:
        """
        Build per-frame interpolation descriptors for smooth animations.

        Args:
            num_keyframes (int): Number of anchor states.
            hold_frames (int): Number of repeated anchor frames.
            transition_frames (int): Number of interpolated in-between frames.

        Returns:
            list[tuple[int, int, float]]: Frame specs as
            ``(left_index, right_index, alpha)``.

        Raises:
            ValueError: Not raised directly by this method.
        """
        n = int(num_keyframes)
        hold = max(1, int(hold_frames))
        trans = max(0, int(transition_frames))
        specs: list[tuple[int, int, float]] = []
        if n <= 0:
            return specs
        for idx in range(n):
            for _ in range(hold):
                specs.append((idx, idx, 0.0))
            if idx < n - 1 and trans > 0:
                for step in range(1, trans + 1):
                    alpha = float(step) / float(trans + 1)
                    specs.append((idx, idx + 1, alpha))
        return specs

    @staticmethod
    def _interpolate_series(
        x0: np.ndarray,
        y0: np.ndarray,
        x1: np.ndarray,
        y1: np.ndarray,
        alpha: float,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Interpolate two plotted series onto a shared x-axis.

        Args:
            x0 (np.ndarray): Left-state x coordinates.
            y0 (np.ndarray): Left-state y coordinates.
            x1 (np.ndarray): Right-state x coordinates.
            y1 (np.ndarray): Right-state y coordinates.
            alpha (float): Blend factor in ``[0, 1]``.

        Returns:
            tuple[np.ndarray, np.ndarray]: Interpolated x/y series.

        Raises:
            ValueError: Not raised directly by this method.
        """
        a = float(alpha)
        if a <= 0.0:
            return np.asarray(x0, dtype=float), np.asarray(y0, dtype=float)
        if a >= 1.0:
            return np.asarray(x1, dtype=float), np.asarray(y1, dtype=float)

        x0_arr = np.asarray(x0, dtype=float)
        y0_arr = np.asarray(y0, dtype=float)
        x1_arr = np.asarray(x1, dtype=float)
        y1_arr = np.asarray(y1, dtype=float)

        if len(x0_arr) == 0 and len(x1_arr) == 0:
            return np.asarray([], dtype=float), np.asarray([], dtype=float)
        if len(x0_arr) == 0:
            return x1_arr, y1_arr
        if len(x1_arr) == 0:
            return x0_arr, y0_arr

        x_union = np.array(sorted(set(x0_arr.tolist() + x1_arr.tolist())))
        y0_interp = np.interp(
            x_union,
            x0_arr,
            y0_arr,
            left=float(y0_arr[0]),
            right=float(y0_arr[-1]),
        )
        y1_interp = np.interp(
            x_union,
            x1_arr,
            y1_arr,
            left=float(y1_arr[0]),
            right=float(y1_arr[-1]),
        )
        y_interp = (1.0 - a) * y0_interp + a * y1_interp
        return x_union, y_interp

    def _series_xy_err(
        self,
        stats_list: list[dict[str, Any]] | None,
        mean_field: str = "mean",
        err_field: str = "std",
        use_sem: bool = False,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Convert depth-indexed stats entries into finite x/y/error arrays.

        Args:
            stats_list (list[dict[str, Any]] | None): Per-depth stats rows.
            mean_field (str): Mean-value field to extract per depth.
            err_field (str): Error field to extract per depth.
            use_sem (bool): If ``True``, convert std to SEM using
                ``plotter.num_cliffs``.

        Returns:
            tuple[np.ndarray, np.ndarray, np.ndarray]: Numeric x/y/error arrays
            after invalid rows are filtered out.

        Raises:
            ValueError: Not raised directly by this method.
        """
        means = self.plotter._extract_series(
            stats_list,
            mean_field,
            len(self.plotter.depths),
        )
        errs = self.plotter._extract_series(
            stats_list,
            err_field,
            len(self.plotter.depths),
        )
        x, y, e = self.plotter._mask_invalid(self.plotter.depths, means, errs)

        x_arr = np.asarray(x, dtype=float)
        y_arr = np.asarray(y, dtype=float)
        e_arr = np.asarray(e, dtype=float)

        if use_sem:
            n_seq = max(int(getattr(self.plotter, "num_cliffs", 1)), 1)
            if n_seq > 1:
                e_arr = e_arr / np.sqrt(float(n_seq))

        e_arr = np.where(np.isfinite(e_arr), np.maximum(0.0, e_arr), 0.0)
        return x_arr, y_arr, e_arr

    def _series_xy(
        self,
        stats_list: list[dict[str, Any]] | None,
        field: str = "mean",
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Backward-compatible x/y extraction helper.

        Args:
            stats_list (list[dict[str, Any]] | None): Per-depth stats rows.
            field (str): Metric field to extract from each stats entry.

        Returns:
            tuple[np.ndarray, np.ndarray]: Numeric x/y arrays.

        Raises:
            ValueError: Not raised directly by this method.
        """
        x, y, _ = self._series_xy_err(
            stats_list=stats_list,
            mean_field=field,
            err_field="std",
            use_sem=False,
        )
        return x, y

    @staticmethod
    def _tight_ylim(
        values: list[float],
        low_default: float,
        high_default: float,
        pad_frac: float = 0.05,
        min_span: float = 0.03,
    ) -> tuple[float, float]:
        """
        Compute a padded y-range from sample values with safe defaults.

        Args:
            values (list[float]): Candidate y-values used for bounds.
            low_default (float): Fallback lower bound when data are empty.
            high_default (float): Fallback upper bound when data are empty.
            pad_frac (float): Fractional padding applied to the span.
            min_span (float): Minimum allowed span before padding.

        Returns:
            tuple[float, float]: Computed ``(y_min, y_max)`` limits.

        Raises:
            ValueError: Not raised directly by this method.
        """
        finite = [float(v) for v in values if np.isfinite(v)]
        if not finite:
            return low_default, high_default
        v_min = float(np.min(finite))
        v_max = float(np.max(finite))
        span = max(v_max - v_min, float(min_span))
        pad = span * float(pad_frac)
        return v_min - pad, v_max + pad

    def _probability_label(self, prob: float) -> str:
        """
        Format one probability value for compact figure titles.

        Args:
            prob (float): Probability value.

        Returns:
            str: Scientific-notation label string.

        Raises:
            ValueError: Not raised directly by this method.
        """
        return f"{float(prob):.2e}"

    def create_const_sweep_gif(
        self,
        const_check: int = 0,
        output_name: str | None = None,
        strict: bool = True,
    ) -> str:
        """
        Animate RB/LRB curves for fixed ``const_check`` while sweeping all ``p``.

        Args:
            const_check (int): Constant-check value shown in each frame.
            output_name (str | None): Optional GIF filename. When ``None``, a
                default name is derived from ``const_check``.
            strict (bool): If ``True``, missing probability rows raise an
                error. If ``False``, available rows are rendered.

        Returns:
            str: Absolute path to the created GIF file.

        Raises:
            FileNotFoundError: If no required data are available, or if
                ``strict=True`` and some expected rows are missing.
        """
        rows: list[dict[str, Any]] = []
        missing_probs: list[float] = []
        for prob_index, prob in enumerate(self.plotter.probabilities):
            ok_lrb, lrb, ok_rb, rb = self.plotter._read_pair(
                check_type="const",
                check_num=int(const_check),
                prob_index=prob_index,
            )
            if not ok_lrb:
                missing_probs.append(float(prob))
                continue
            rows.append(
                {
                    "p": float(prob),
                    "lrb_f": lrb[1],
                    "rb_f": rb[1] if ok_rb else None,
                }
            )

        if strict and missing_probs:
            raise FileNotFoundError(
                "Missing const-check CSV files for probabilities: "
                + ", ".join(f"{p:.6g}" for p in missing_probs)
            )
        if not rows:
            raise FileNotFoundError(
                f"No const-check data found for const={int(const_check)}."
            )

        y_values: list[float] = []
        for row in rows:
            _, y_l, e_l = self._series_xy_err(row["lrb_f"])
            y_values.extend(float(v) for v in (y_l - e_l))
            y_values.extend(float(v) for v in (y_l + e_l))
            if row["rb_f"] is not None:
                _, y_r, e_r = self._series_xy_err(row["rb_f"])
                y_values.extend(float(v) for v in (y_r - e_r))
                y_values.extend(float(v) for v in (y_r + e_r))
        y_min, y_max = self._tight_ylim(
            values=y_values,
            low_default=-0.03,
            high_default=1.03,
            pad_frac=0.06,
            min_span=0.05,
        )
        y_min = max(-0.03, y_min)
        y_max = min(1.2, y_max)

        fig, ax = plt.subplots(figsize=self.render_config.figsize_const)
        lrb_color, rb_color = self._default_curve_colors()
        frame_specs = self._build_transition_frame_specs(
            num_keyframes=len(rows),
            hold_frames=self.render_config.hold_frames,
            transition_frames=self.render_config.transition_frames,
        )

        def update(frame_index: int) -> None:
            left_idx, right_idx, alpha = frame_specs[int(frame_index)]
            row_left = rows[left_idx]
            row_right = rows[right_idx]
            prob = ((1.0 - alpha) * float(row_left["p"])) + (
                alpha * float(row_right["p"])
            )
            ax.clear()

            x_l_0, y_l_0, e_l_0 = self._series_xy_err(row_left["lrb_f"])
            x_l_1, y_l_1, e_l_1 = self._series_xy_err(row_right["lrb_f"])
            x_l, y_l = self._interpolate_series(
                x_l_0,
                y_l_0,
                x_l_1,
                y_l_1,
                alpha,
            )
            _, e_l = self._interpolate_series(
                x_l_0,
                e_l_0,
                x_l_1,
                e_l_1,
                alpha,
            )
            ax.errorbar(
                x_l,
                y_l,
                yerr=e_l,
                fmt="o-",
                color=lrb_color,
                linewidth=1.5,
                capsize=2,
                label=self._lrb_label(),
            )

            if row_left["rb_f"] is not None or row_right["rb_f"] is not None:
                x_r_0, y_r_0, e_r_0 = (
                    self._series_xy_err(row_left["rb_f"])
                    if row_left["rb_f"] is not None
                    else (
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                    )
                )
                x_r_1, y_r_1, e_r_1 = (
                    self._series_xy_err(row_right["rb_f"])
                    if row_right["rb_f"] is not None
                    else (
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                    )
                )
                x_r, y_r = self._interpolate_series(
                    x_r_0,
                    y_r_0,
                    x_r_1,
                    y_r_1,
                    alpha,
                )
                _, e_r = self._interpolate_series(
                    x_r_0,
                    e_r_0,
                    x_r_1,
                    e_r_1,
                    alpha,
                )
                ax.errorbar(
                    x_r,
                    y_r,
                    yerr=e_r,
                    fmt="s-",
                    color=rb_color,
                    linewidth=1.5,
                    capsize=2,
                    label="RB",
                )

            ax.set_xlabel("Depth")
            ax.set_ylabel("Expectation Value of Logical X")
            ax.set_ylim(y_min, y_max)
            ax.set_xticks(self.plotter.depths)
            ax.set_title(
                f"const={int(const_check)}   |   p = {self._probability_label(prob)}",
                fontsize=14,
            )
            ax.legend(loc="upper right")
            ax.grid(False)

        animation = FuncAnimation(
            fig,
            update,
            frames=len(frame_specs),
            interval=1000 / max(self.render_config.fps, 1),
            blit=False,
            repeat=True,
        )

        file_name = (
            output_name
            if output_name is not None
            else f"const-{int(const_check)}-rb-lrb-vs-p.gif"
        )
        out_path = self.out_dir / file_name
        animation.save(
            out_path,
            writer=PillowWriter(fps=max(self.render_config.fps, 1)),
            dpi=int(self.render_config.dpi),
        )
        plt.close(fig)
        return str(out_path)

    def create_unif_interval_sweep_gif(
        self,
        prob_index: int,
        interval_min: int = 1,
        interval_max: int = 22,
        output_name: str | None = None,
        strict: bool = True,
    ) -> str:
        """
        Animate one probability across uniform-interval checks, including
        rejected-run traces.

        Args:
            prob_index (int): Probability-row index to animate.
            interval_min (int): Inclusive minimum interval check value.
            interval_max (int): Inclusive maximum interval check value.
            output_name (str | None): Optional GIF filename. When ``None``, a
                name is derived from probability metadata.
            strict (bool): If ``True``, missing interval-check rows raise an
                error. If ``False``, available rows are rendered.

        Returns:
            str: Absolute path to the created GIF file.

        Raises:
            IndexError: If ``prob_index`` is outside the run probability range.
            ValueError: If interval bounds produce an empty check set.
            FileNotFoundError: If no required data are available, or if
                ``strict=True`` and some expected interval rows are missing.
        """
        prob_index = int(prob_index)
        if prob_index < 0 or prob_index >= len(self.plotter.probabilities):
            raise IndexError(
                f"prob_index={prob_index} is outside [0, {len(self.plotter.probabilities) - 1}]"
            )

        checks = (
            self.plotter.stab_unif
            if self.plotter.stab_unif
            else list(range(1, 23))
        )
        checks = [
            int(c)
            for c in checks
            if int(interval_min) <= int(c) <= int(interval_max)
        ]
        checks = sorted(set(checks))
        if not checks:
            raise ValueError(
                f"No uniform checks in range [{int(interval_min)}, {int(interval_max)}]."
            )

        rows: list[dict[str, Any]] = []
        missing_checks: list[int] = []
        for check in checks:
            ok_lrb, lrb, ok_rb, rb = self.plotter._read_pair(
                check_type="unif",
                check_num=int(check),
                prob_index=prob_index,
            )
            if not ok_lrb:
                missing_checks.append(int(check))
                continue
            rows.append(
                {
                    "check": int(check),
                    "lrb_f": lrb[1],
                    "lrb_r": lrb[2],
                    "rb_f": rb[1] if ok_rb else None,
                }
            )

        if strict and missing_checks:
            raise FileNotFoundError(
                f"Missing unif-check CSV files for p-index {prob_index}: "
                + ", ".join(str(v) for v in missing_checks)
            )
        if not rows:
            raise FileNotFoundError(
                f"No unif-check data found for p-index {prob_index}."
            )

        y_main_values: list[float] = []
        y_rej_values: list[float] = []
        for row in rows:
            _, y_l, e_l = self._series_xy_err(row["lrb_f"])
            y_main_values.extend(float(v) for v in (y_l - e_l))
            y_main_values.extend(float(v) for v in (y_l + e_l))
            if row["rb_f"] is not None:
                _, y_r, e_r = self._series_xy_err(row["rb_f"])
                y_main_values.extend(float(v) for v in (y_r - e_r))
                y_main_values.extend(float(v) for v in (y_r + e_r))
            _, y_rej, e_rej = self._series_xy_err(
                row["lrb_r"],
                use_sem=True,
            )
            y_rej_values.extend(float(v) for v in np.maximum(0.0, y_rej - e_rej))
            y_rej_values.extend(float(v) for v in np.minimum(1.0, y_rej + e_rej))

        y_main_min, y_main_max = self._tight_ylim(
            values=y_main_values,
            low_default=-0.03,
            high_default=1.03,
            pad_frac=0.06,
            min_span=0.05,
        )
        y_main_min = max(-0.03, y_main_min)
        y_main_max = min(1.2, y_main_max)

        y_rej_min, y_rej_max = self._tight_ylim(
            values=y_rej_values,
            low_default=-0.03,
            high_default=1.03,
            pad_frac=0.08,
            min_span=0.02,
        )
        y_rej_min = max(-0.03, y_rej_min)
        y_rej_max = min(1.03, y_rej_max)

        prob = float(self.plotter.probabilities[prob_index])
        fig, axes = plt.subplots(
            nrows=1,
            ncols=2,
            figsize=self.render_config.figsize_unif,
            constrained_layout=True,
        )
        ax_main, ax_rej = axes
        lrb_color, rb_color = self._default_curve_colors()
        frame_specs = self._build_transition_frame_specs(
            num_keyframes=len(rows),
            hold_frames=self.render_config.hold_frames,
            transition_frames=self.render_config.transition_frames,
        )

        def update(frame_index: int) -> None:
            left_idx, right_idx, alpha = frame_specs[int(frame_index)]
            row_left = rows[left_idx]
            row_right = rows[right_idx]
            check_blend = ((1.0 - alpha) * float(row_left["check"])) + (
                alpha * float(row_right["check"])
            )
            check_int = int(np.round(check_blend))
            check_label = str(check_int)
            ax_main.clear()
            ax_rej.clear()

            x_l_0, y_l_0, e_l_0 = self._series_xy_err(row_left["lrb_f"])
            x_l_1, y_l_1, e_l_1 = self._series_xy_err(row_right["lrb_f"])
            x_l, y_l = self._interpolate_series(
                x_l_0,
                y_l_0,
                x_l_1,
                y_l_1,
                alpha,
            )
            _, e_l = self._interpolate_series(
                x_l_0,
                e_l_0,
                x_l_1,
                e_l_1,
                alpha,
            )
            ax_main.errorbar(
                x_l,
                y_l,
                yerr=e_l,
                fmt="o-",
                color=lrb_color,
                linewidth=1.4,
                capsize=2,
                label=self._lrb_label(),
            )
            if row_left["rb_f"] is not None or row_right["rb_f"] is not None:
                x_r_0, y_r_0, e_r_0 = (
                    self._series_xy_err(row_left["rb_f"])
                    if row_left["rb_f"] is not None
                    else (
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                    )
                )
                x_r_1, y_r_1, e_r_1 = (
                    self._series_xy_err(row_right["rb_f"])
                    if row_right["rb_f"] is not None
                    else (
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                        np.asarray([], dtype=float),
                    )
                )
                x_r, y_r = self._interpolate_series(
                    x_r_0,
                    y_r_0,
                    x_r_1,
                    y_r_1,
                    alpha,
                )
                _, e_r = self._interpolate_series(
                    x_r_0,
                    e_r_0,
                    x_r_1,
                    e_r_1,
                    alpha,
                )
                ax_main.errorbar(
                    x_r,
                    y_r,
                    yerr=e_r,
                    fmt="s-",
                    color=rb_color,
                    linewidth=1.4,
                    capsize=2,
                    label="RB",
                )
            ax_main.set_title(
                f"p = {self._probability_label(prob)}   |   interval = {check_label}"
            )
            ax_main.set_xlabel("Depth")
            ax_main.set_ylabel("Expectation Value of Logical X")
            ax_main.set_ylim(y_main_min, y_main_max)
            ax_main.set_xticks(self.plotter.depths)
            ax_main.grid(False)

            x_rej_0, y_rej_0, e_rej_0 = self._series_xy_err(
                row_left["lrb_r"],
                use_sem=True,
            )
            x_rej_1, y_rej_1, e_rej_1 = self._series_xy_err(
                row_right["lrb_r"],
                use_sem=True,
            )
            x_rej, y_rej = self._interpolate_series(
                x_rej_0,
                y_rej_0,
                x_rej_1,
                y_rej_1,
                alpha,
            )
            _, e_rej = self._interpolate_series(
                x_rej_0,
                e_rej_0,
                x_rej_1,
                e_rej_1,
                alpha,
            )
            low = np.maximum(0.0, y_rej - e_rej)
            high = np.minimum(1.0, y_rej + e_rej)
            yerr = np.vstack([y_rej - low, high - y_rej])
            ax_rej.errorbar(
                x_rej,
                y_rej,
                yerr=yerr,
                fmt="d-",
                color="#2ca02c",
                linewidth=1.4,
                capsize=2,
                label="_nolegend_",
            )
            ax_rej.set_title(f"Rejected runs   |   interval = {check_label}")
            ax_rej.set_xlabel("Depth")
            ax_rej.set_ylabel("Proportion Rejected")
            ax_rej.set_ylim(y_rej_min, y_rej_max)
            ax_rej.set_xticks(self.plotter.depths)
            legend_handles = [
                Line2D(
                    [0],
                    [0],
                    color=lrb_color,
                    marker="o",
                    linestyle="-",
                    label=self._lrb_label(),
                ),
            ]
            if row_left["rb_f"] is not None or row_right["rb_f"] is not None:
                legend_handles.append(
                    Line2D(
                        [0],
                        [0],
                        color=rb_color,
                        marker="s",
                        linestyle="-",
                        label="RB",
                    )
                )
            legend_handles.append(
                Line2D(
                    [0],
                    [0],
                    color="#2ca02c",
                    marker="d",
                    linestyle="-",
                    label=f"LRB rejected on {self._code_label()}",
                )
            )
            ax_rej.legend(handles=legend_handles, loc="lower right")
            ax_rej.grid(False)

        animation = FuncAnimation(
            fig,
            update,
            frames=len(frame_specs),
            interval=1000 / max(self.render_config.fps, 1),
            blit=False,
            repeat=True,
        )

        file_name = (
            output_name
            if output_name is not None
            else (
                f"unif-interval-sweep-pidx{prob_index:02d}-"
                f"p{self._probability_label(prob)}.gif"
            )
        )
        out_path = self.out_dir / file_name
        animation.save(
            out_path,
            writer=PillowWriter(fps=max(self.render_config.fps, 1)),
            dpi=int(self.render_config.dpi),
        )
        plt.close(fig)
        return str(out_path)

    def create_unif_interval_gifs_for_all_probabilities(
        self,
        interval_min: int = 1,
        interval_max: int = 22,
        strict: bool = True,
    ) -> list[str]:
        """
        Create one interval-sweep GIF for each available probability index.

        Args:
            interval_min (int): Inclusive minimum interval check value.
            interval_max (int): Inclusive maximum interval check value.
            strict (bool): Forwarded strictness for missing interval rows.

        Returns:
            list[str]: Paths of generated GIF files in probability-index order.

        Raises:
            IndexError: Propagated from per-probability generation.
            ValueError: Propagated when interval bounds are invalid.
            FileNotFoundError: Propagated when expected CSV rows are missing.
        """
        outputs: list[str] = []
        for prob_index in range(len(self.plotter.probabilities)):
            path = self.create_unif_interval_sweep_gif(
                prob_index=prob_index,
                interval_min=interval_min,
                interval_max=interval_max,
                strict=strict,
            )
            outputs.append(path)
        return outputs
